# Generated by Django 5.2.7 on 2025-10-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplyApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Apply First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apply Last Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Apply Email"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Apply Phone Number"),
                ),
                (
                    "education_degree",
                    models.CharField(
                        max_length=100, verbose_name="Apply Education Degree"
                    ),
                ),
                (
                    "study_field",
                    models.CharField(max_length=100, verbose_name="Apply Study Field"),
                ),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes/", verbose_name="Apply Resume File"
                    ),
                ),
                ("cover_letter", models.TextField(verbose_name="Apply Cover Letter")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("RV", "Reviewed"),
                            ("RJ", "Rejected"),
                            ("A", "Accepted"),
                        ],
                        default="P",
                        max_length=2,
                        verbose_name="Apply Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Apply Application",
                "verbose_name_plural": "Apply Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Contact First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Contact Last Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Contact Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=50, verbose_name="Contact Phone Number"
                    ),
                ),
                ("message", models.TextField(verbose_name="Contact Message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="Order Company Name"),
                ),
                (
                    "activity_area",
                    models.CharField(
                        max_length=100, verbose_name="Order Activity Area"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Order Email"),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=50, verbose_name="Order Contact Number"
                    ),
                ),
                ("explanation", models.TextField(verbose_name="Order Explanation")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
