# Generated by Django 5.2.7 on 2025-10-04 09:21

from django.db import migrations, models

import apps.submissions.validators


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyapplication",
            name="resume",
            field=models.FileField(
                upload_to="resumes/",
                validators=[apps.submissions.validators.validate_resume],
                verbose_name="Apply Resume File",
            ),
        ),
    ]
