# Generated by Django 5.2.7 on 2025-10-06 10:09

import autoslug.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Blog Title")),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Blog Title"
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Blog Title"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="title",
                        unique=True,
                        verbose_name="Blog Slug",
                    ),
                ),
                (
                    "slug_en",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        null=True,
                        populate_from="title",
                        unique=True,
                        verbose_name="Blog Slug",
                    ),
                ),
                (
                    "slug_fa",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        null=True,
                        populate_from="title",
                        unique=True,
                        verbose_name="Blog Slug",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Blog Description"),
                ),
                (
                    "description_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Blog Description"
                    ),
                ),
                (
                    "description_fa",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Blog Description"
                    ),
                ),
                (
                    "summary",
                    models.CharField(max_length=255, verbose_name="Blog Summary"),
                ),
                (
                    "summary_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Blog Summary"
                    ),
                ),
                (
                    "summary_fa",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Blog Summary"
                    ),
                ),
                (
                    "body",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Blog Content"
                    ),
                ),
                (
                    "body_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Blog Content"
                    ),
                ),
                (
                    "body_fa",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Blog Content"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(upload_to="blogs/", verbose_name="Blog Cover"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Published"), ("A", "Archived")],
                        default="P",
                        verbose_name="Blog Status",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-updated_at", "-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Category Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Category Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Category Title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Approved"), ("R", "Rejected")],
                        default="A",
                        max_length=1,
                        verbose_name="Comment Status",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portfolio.blog",
                        verbose_name="Blog",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="portfolio.comment",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Project Title"),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Project Title"
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Project Title"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="title",
                        unique=True,
                        verbose_name="Project Slug",
                    ),
                ),
                (
                    "slug_en",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        null=True,
                        populate_from="title",
                        unique=True,
                        verbose_name="Project Slug",
                    ),
                ),
                (
                    "slug_fa",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        null=True,
                        populate_from="title",
                        unique=True,
                        verbose_name="Project Slug",
                    ),
                ),
                ("description", models.TextField(verbose_name="Project Description")),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Project Description"),
                ),
                (
                    "description_fa",
                    models.TextField(null=True, verbose_name="Project Description"),
                ),
                ("size", models.CharField(verbose_name="Project Size")),
                (
                    "dimensions",
                    models.CharField(max_length=255, verbose_name="Project dimensions"),
                ),
                (
                    "creation_year",
                    models.CharField(
                        max_length=4, verbose_name="Project Creation Year"
                    ),
                ),
                ("scale", models.CharField(verbose_name="Project Scale")),
                (
                    "status",
                    models.CharField(
                        choices=[("F", "Finished"), ("O", "Ongoing")],
                        default="F",
                        max_length=1,
                        verbose_name="Project Status",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="portfolio.category",
                        verbose_name="Project Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Gallery Item Image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="portfolio.project",
                        verbose_name="Gallery Item Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["created_at"],
            },
        ),
    ]
