# Generated by Django 5.2.7 on 2025-10-05 11:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="body_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Blog Content"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="body_fa",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Blog Content"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="description_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Blog Description"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="description_fa",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Blog Description"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="summary_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Blog Summary"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="summary_fa",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Blog Summary"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Blog Title"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_fa",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Blog Title"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Category Title"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_fa",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Category Title"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Project Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_fa",
            field=models.TextField(null=True, verbose_name="Project Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Project Title"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_fa",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Project Title"
            ),
        ),
    ]
