# Generated by Django 5.2.7 on 2025-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="size",
            field=models.CharField(verbose_name="Project Size"),
        ),
    ]
