# Generated by Django 5.2.7 on 2025-10-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-updated_at", "-created_at", "title"],
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogsp",
            },
        ),
    ]
