# Generated by Django 5.2.7 on 2025-10-05 11:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blog_body_en_blog_body_fa_blog_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug_en",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Blog Slug",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug_fa",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Blog Slug",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug_en",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Project Slug",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug_fa",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Project Slug",
            ),
        ),
    ]
